name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: cargo test --all-features
      - uses: rust-lang/crates-io-auth-action@v1
        id: cratesio-auth
      - name: Publish crates
        if: ${{ github.event_name == 'push' }}
        run: |
          if ! git show --exit-code -G^version raffia_macro/Cargo.toml; then
            cargo publish -p raffia_macro
          fi
          if ! git show --exit-code -G^version raffia/Cargo.toml; then
            cargo publish -p raffia
          fi
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.cratesio-auth.outputs.token }}

  playground:
    name: playground
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack build --target web --no-typescript wasm
      - name: Deploy Production
        run: |
          npm i --location=global netlify-cli
          netlify deploy --site=3c60cb99-3e5c-4e0e-9f69-d1952439e0b5 --dir=wasm/pkg --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
